version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
